create table if not exists public.odyssey_debug_perf_log (
  id bigint generated by default as identity primary key,
  trace_id text not null default '',
  parent_id text not null default '',
  function_name text not null,
  span_name text not null,
  phase_name text not null default '',
  level text not null default 'info',
  duration_ms numeric(12,2) not null default 0,
  character_id uuid null,
  actor_character_id uuid null,
  target_character_id uuid null,
  character_key text not null default '',
  room_id text not null default '',
  scene_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  error_code text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists odyssey_debug_perf_log_created_at_idx
  on public.odyssey_debug_perf_log (created_at desc, id desc);

create index if not exists odyssey_debug_perf_log_trace_id_idx
  on public.odyssey_debug_perf_log (trace_id, created_at desc);

create index if not exists odyssey_debug_perf_log_function_name_idx
  on public.odyssey_debug_perf_log (function_name, created_at desc);

create index if not exists odyssey_debug_perf_log_character_id_idx
  on public.odyssey_debug_perf_log (character_id, created_at desc);

alter table public.odyssey_debug_perf_log enable row level security;

drop policy if exists "odyssey_debug_perf_log_full_access" on public.odyssey_debug_perf_log;
create policy "odyssey_debug_perf_log_full_access"
on public.odyssey_debug_perf_log
for all
to anon, authenticated
using (true)
with check (true);

grant select, insert, delete on public.odyssey_debug_perf_log to anon, authenticated;

create or replace function public.odyssey_debug_perf(
  p_function_name text,
  p_span_name text,
  p_phase_name text default '',
  p_trace_id text default '',
  p_parent_id text default '',
  p_level text default 'info',
  p_duration_ms numeric default 0,
  p_character_id uuid default null,
  p_actor_character_id uuid default null,
  p_target_character_id uuid default null,
  p_character_key text default '',
  p_room_id text default '',
  p_scene_id text default '',
  p_metadata jsonb default '{}'::jsonb,
  p_error_code text default ''
)
returns void
language plpgsql
as $body$
begin
  insert into public.odyssey_debug_perf_log (
    trace_id,
    parent_id,
    function_name,
    span_name,
    phase_name,
    level,
    duration_ms,
    character_id,
    actor_character_id,
    target_character_id,
    character_key,
    room_id,
    scene_id,
    metadata,
    error_code
  )
  values (
    trim(coalesce(p_trace_id, '')),
    trim(coalesce(p_parent_id, '')),
    coalesce(nullif(trim(coalesce(p_function_name, '')), ''), 'unknown_function'),
    coalesce(nullif(trim(coalesce(p_span_name, '')), ''), 'unknown_span'),
    trim(coalesce(p_phase_name, '')),
    case lower(coalesce(p_level, 'info'))
      when 'error' then 'error'
      when 'warn' then 'warn'
      else 'info'
    end,
    greatest(0, coalesce(p_duration_ms, 0)),
    p_character_id,
    p_actor_character_id,
    p_target_character_id,
    trim(coalesce(p_character_key, '')),
    trim(coalesce(p_room_id, '')),
    trim(coalesce(p_scene_id, '')),
    case
      when jsonb_typeof(p_metadata) = 'object' then p_metadata
      when p_metadata is null then '{}'::jsonb
      else jsonb_build_object('value', p_metadata)
    end,
    trim(coalesce(p_error_code, ''))
  );
end;
$body$;

create or replace function public.get_odyssey_debug_perf_log(
  p_limit integer default 200,
  p_trace_id text default null
)
returns table (
  id bigint,
  trace_id text,
  parent_id text,
  function_name text,
  span_name text,
  phase_name text,
  level text,
  duration_ms numeric,
  character_id uuid,
  actor_character_id uuid,
  target_character_id uuid,
  character_key text,
  room_id text,
  scene_id text,
  metadata jsonb,
  error_code text,
  created_at timestamptz
)
language sql
as $body$
  select
    log.id,
    log.trace_id,
    log.parent_id,
    log.function_name,
    log.span_name,
    log.phase_name,
    log.level,
    log.duration_ms,
    log.character_id,
    log.actor_character_id,
    log.target_character_id,
    log.character_key,
    log.room_id,
    log.scene_id,
    log.metadata,
    log.error_code,
    log.created_at
  from public.odyssey_debug_perf_log log
  where (
    coalesce(nullif(trim(coalesce(p_trace_id, '')), ''), '') = ''
    or log.trace_id = trim(p_trace_id)
  )
  order by log.created_at desc, log.id desc
  limit greatest(1, least(coalesce(p_limit, 200), 500));
$body$;

grant execute on function public.odyssey_debug_perf(
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  jsonb,
  text
) to anon, authenticated;

grant execute on function public.get_odyssey_debug_perf_log(integer, text) to anon, authenticated;

create or replace function public.upsert_odyssey_character_sheet(p_payload jsonb)
returns jsonb
language plpgsql
as $body$
declare
  v_trace_id text := trim(coalesce(p_payload->>'trace_id', ''));
  v_function_name constant text := 'upsert_odyssey_character_sheet';
  v_total_started_at timestamptz := clock_timestamp();
  v_phase_started_at timestamptz := clock_timestamp();
  v_duration_ms numeric(12,2) := 0;
  v_row_count integer := 0;
  v_character_key text := trim(coalesce(p_payload->>'character_key', ''));
  v_character_id uuid;
  v_character_bucket text := case lower(coalesce(p_payload->>'character_bucket', 'player'))
    when 'npc_template' then 'npc_template'
    when 'npc_active' then 'npc_active'
    else 'player'
  end;
  v_source_template_key text := trim(coalesce(p_payload->>'source_template_key', ''));
  v_enabled boolean := coalesce((p_payload->>'enabled')::boolean, true);
  v_tracker_minor integer := greatest(0, least(4, coalesce((p_payload->>'tracker_minor')::integer, 0)));
  v_tracker_serious integer := greatest(0, least(2, coalesce((p_payload->>'tracker_serious')::integer, 0)));
  v_owner_player_id text := coalesce(p_payload->>'owner_player_id', '');
  v_owner_player_name text := coalesce(p_payload->>'owner_player_name', '');
  v_campaign_id text := trim(coalesce(p_payload->>'campaign_id', ''));
  v_room_id text := trim(coalesce(p_payload->>'room_id', ''));
  v_resources jsonb := case
    when jsonb_typeof(p_payload->'resources') = 'object' then p_payload->'resources'
    else '{}'::jsonb
  end;
  v_result jsonb := '{}'::jsonb;
begin
  v_phase_started_at := clock_timestamp();
  if v_character_key = '' then
    raise exception 'character_key is required';
  end if;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'validate',
    p_phase_name => 'validate',
    p_trace_id => v_trace_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'character_bucket', v_character_bucket,
      'enabled', v_enabled
    )
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_characters (
    character_key,
    character_bucket,
    source_template_key,
    enabled,
    tracker_minor,
    tracker_serious,
    owner_player_id,
    owner_player_name,
    campaign_id,
    room_id,
    resources,
    is_deleted
  )
  values (
    v_character_key,
    v_character_bucket,
    v_source_template_key,
    v_enabled,
    v_tracker_minor,
    v_tracker_serious,
    v_owner_player_id,
    v_owner_player_name,
    v_campaign_id,
    v_room_id,
    v_resources,
    false
  )
  on conflict (character_key) do update
  set
    character_bucket = excluded.character_bucket,
    source_template_key = excluded.source_template_key,
    enabled = excluded.enabled,
    tracker_minor = excluded.tracker_minor,
    tracker_serious = excluded.tracker_serious,
    owner_player_id = excluded.owner_player_id,
    owner_player_name = excluded.owner_player_name,
    campaign_id = excluded.campaign_id,
    room_id = excluded.room_id,
    resources = excluded.resources,
    is_deleted = false
  returning id into v_character_id;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'upsert-character',
    p_phase_name => 'upsert-character',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'character_bucket', v_character_bucket,
      'tracker_minor', v_tracker_minor,
      'tracker_serious', v_tracker_serious
    )
  );

  v_phase_started_at := clock_timestamp();
  delete from public.odyssey_character_characteristics where character_id = v_character_id;
  delete from public.odyssey_character_skills where character_id = v_character_id;
  delete from public.odyssey_character_weapons where character_id = v_character_id;
  delete from public.odyssey_character_body_parts where character_id = v_character_id;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'clear-child-records',
    p_phase_name => 'clear-child-records',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_character_characteristics (
    character_id,
    key,
    label,
    value,
    sort_order
  )
  select
    v_character_id,
    trim(coalesce(entry.value->>'key', '')),
    coalesce(nullif(trim(entry.value->>'label'), ''), trim(coalesce(entry.value->>'key', ''))),
    greatest(0, least(20, coalesce((entry.value->>'value')::integer, 0))),
    coalesce((entry.value->>'sort_order')::integer, entry.ordinality - 1)
  from jsonb_array_elements(
    case
      when jsonb_typeof(p_payload->'characteristics') = 'array' then p_payload->'characteristics'
      else '[]'::jsonb
    end
  ) with ordinality as entry(value, ordinality)
  where trim(coalesce(entry.value->>'key', '')) <> '';
  get diagnostics v_row_count = row_count;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'insert-characteristics',
    p_phase_name => 'insert-characteristics',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object('row_count', v_row_count)
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_character_skills (
    character_id,
    name,
    value,
    category,
    strength_bonus,
    sort_order
  )
  select
    v_character_id,
    trim(coalesce(entry.value->>'name', '')),
    greatest(0, least(10, coalesce((entry.value->>'value')::integer, 0))),
    case lower(coalesce(entry.value->>'category', 'applied'))
      when 'combat' then 'combat'
      when 'abilities' then 'abilities'
      else 'applied'
    end,
    coalesce((entry.value->>'strength_bonus')::boolean, false),
    coalesce((entry.value->>'sort_order')::integer, entry.ordinality - 1)
  from jsonb_array_elements(
    case
      when jsonb_typeof(p_payload->'skills') = 'array' then p_payload->'skills'
      else '[]'::jsonb
    end
  ) with ordinality as entry(value, ordinality)
  where trim(coalesce(entry.value->>'name', '')) <> '';
  get diagnostics v_row_count = row_count;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'insert-skills',
    p_phase_name => 'insert-skills',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object('row_count', v_row_count)
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_character_weapons (
    character_id,
    weapon_kind,
    name,
    damage,
    accuracy,
    ammo_current,
    ammo_max,
    sort_order
  )
  select
    v_character_id,
    case lower(coalesce(entry.value->>'weapon_kind', 'melee'))
      when 'ranged' then 'ranged'
      else 'melee'
    end,
    coalesce(nullif(trim(entry.value->>'name'), ''), 'Weapon'),
    greatest(-99, least(99, coalesce((entry.value->>'damage')::integer, 0))),
    greatest(-99, least(99, coalesce((entry.value->>'accuracy')::integer, 0))),
    greatest(0, coalesce((entry.value->>'ammoCurrent')::integer, (entry.value->>'ammo_current')::integer, 0)),
    greatest(0, coalesce((entry.value->>'ammoMax')::integer, (entry.value->>'ammo_max')::integer, 0)),
    coalesce((entry.value->>'sort_order')::integer, entry.ordinality - 1)
  from jsonb_array_elements(
    case
      when jsonb_typeof(p_payload->'weapons') = 'array' then p_payload->'weapons'
      else '[]'::jsonb
    end
  ) with ordinality as entry(value, ordinality);
  get diagnostics v_row_count = row_count;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'insert-weapons',
    p_phase_name => 'insert-weapons',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object('row_count', v_row_count)
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_character_body_parts (
    character_id,
    part_key,
    current_hp,
    max_hp,
    armor,
    minor,
    serious,
    critical,
    max_critical,
    destroyed,
    disabled,
    notes,
    sort_order
  )
  select
    v_character_id,
    trim(coalesce(entry.value->>'part_key', '')),
    greatest(0, coalesce((entry.value->>'current_hp')::integer, 0)),
    greatest(0, coalesce((entry.value->>'max_hp')::integer, 0)),
    greatest(0, coalesce((entry.value->>'armor')::integer, 0)),
    greatest(0, least(3, coalesce((entry.value->>'minor')::integer, 0))),
    greatest(0, least(1, coalesce((entry.value->>'serious')::integer, 0))),
    greatest(0, coalesce((entry.value->>'critical')::integer, 0)),
    greatest(0, coalesce((entry.value->>'max_critical')::integer, (entry.value->>'max_hp')::integer, 0)),
    coalesce((entry.value->>'destroyed')::boolean, false),
    coalesce((entry.value->>'disabled')::boolean, false),
    coalesce(entry.value->>'notes', ''),
    coalesce((entry.value->>'sort_order')::integer, entry.ordinality - 1)
  from jsonb_array_elements(
    case
      when jsonb_typeof(p_payload->'body_parts') = 'array' then p_payload->'body_parts'
      else '[]'::jsonb
    end
  ) with ordinality as entry(value, ordinality)
  where trim(coalesce(entry.value->>'part_key', '')) in ('Head', 'L.Arm', 'R.Arm', 'Torso', 'L.Leg', 'R.Leg', 'Shield', 'Special');
  get diagnostics v_row_count = row_count;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'insert-body-parts',
    p_phase_name => 'insert-body-parts',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object('row_count', v_row_count)
  );

  v_phase_started_at := clock_timestamp();
  perform public.recompute_odyssey_character_combat_state(v_character_id);
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'recompute-combat-state',
    p_phase_name => 'recompute-combat-state',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms
  );

  v_phase_started_at := clock_timestamp();
  v_result := public.get_odyssey_character_sheet(v_character_key);
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'return-character-sheet',
    p_phase_name => 'return-character-sheet',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms
  );

  v_duration_ms := (extract(epoch from clock_timestamp() - v_total_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'total',
    p_phase_name => 'total',
    p_trace_id => v_trace_id,
    p_character_id => v_character_id,
    p_character_key => v_character_key,
    p_room_id => v_room_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'characteristics_count', case when jsonb_typeof(p_payload->'characteristics') = 'array' then jsonb_array_length(p_payload->'characteristics') else 0 end,
      'skills_count', case when jsonb_typeof(p_payload->'skills') = 'array' then jsonb_array_length(p_payload->'skills') else 0 end,
      'weapons_count', case when jsonb_typeof(p_payload->'weapons') = 'array' then jsonb_array_length(p_payload->'weapons') else 0 end,
      'body_parts_count', case when jsonb_typeof(p_payload->'body_parts') = 'array' then jsonb_array_length(p_payload->'body_parts') else 0 end
    )
  );

  return v_result;
exception
  when others then
    perform public.odyssey_debug_perf(
      p_function_name => v_function_name,
      p_span_name => 'error',
      p_phase_name => 'error',
      p_trace_id => v_trace_id,
      p_character_id => v_character_id,
      p_character_key => v_character_key,
      p_room_id => v_room_id,
      p_level => 'error',
      p_duration_ms => (extract(epoch from clock_timestamp() - v_total_started_at) * 1000)::numeric(12,2),
      p_metadata => jsonb_build_object('message', sqlerrm),
      p_error_code => sqlstate
    );
    raise;
end;
$body$;

create or replace function public.apply_damage(p_payload jsonb)
returns jsonb
language plpgsql
as $body$
declare
  v_trace_id text := trim(coalesce(p_payload->>'trace_id', ''));
  v_function_name constant text := 'apply_damage';
  v_total_started_at timestamptz := clock_timestamp();
  v_phase_started_at timestamptz := clock_timestamp();
  v_duration_ms numeric(12,2) := 0;
  v_target_character_id uuid := nullif(trim(coalesce(p_payload->>'target_character_id', '')), '')::uuid;
  v_actor_character_id uuid := nullif(trim(coalesce(p_payload->>'actor_character_id', '')), '')::uuid;
  v_campaign_id text := trim(coalesce(p_payload->>'campaign_id', ''));
  v_room_id text := trim(coalesce(p_payload->>'room_id', ''));
  v_scene_id text := trim(coalesce(p_payload->>'scene_id', ''));
  v_encounter_id uuid := nullif(trim(coalesce(p_payload->>'encounter_id', '')), '')::uuid;
  v_target_part text := coalesce(nullif(trim(coalesce(p_payload->>'target_part', '')), ''), 'Torso');
  v_damage_kind text := lower(coalesce(p_payload->>'damage_kind', 'minor'));
  v_amount integer := greatest(0, coalesce((p_payload->>'amount')::integer, 1));
  v_created_by text := trim(coalesce(p_payload->>'created_by', ''));
  v_target_row public.odyssey_character_body_parts%rowtype;
  v_special_row public.odyssey_character_body_parts%rowtype;
  v_target_result jsonb := '{}'::jsonb;
  v_special_result jsonb := '{}'::jsonb;
  v_overflow_crit integer := 0;
  v_special_hp_loss integer := 0;
  v_special_crit_applied integer := 0;
  v_recomputed jsonb := '{}'::jsonb;
  v_message text := '';
  v_log_entry jsonb := '{}'::jsonb;
begin
  v_phase_started_at := clock_timestamp();
  if v_target_character_id is null then
    raise exception 'target_character_id is required';
  end if;

  if v_target_part not in ('Head', 'L.Arm', 'R.Arm', 'Torso', 'L.Leg', 'R.Leg', 'Shield', 'Special') then
    raise exception 'target_part % is invalid', v_target_part;
  end if;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'validate',
    p_phase_name => 'validate',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'target_part', v_target_part,
      'damage_kind', v_damage_kind,
      'amount', v_amount
    )
  );

  v_phase_started_at := clock_timestamp();
  select *
  into v_target_row
  from public.odyssey_character_body_parts
  where character_id = v_target_character_id
    and part_key = v_target_part;

  if not found then
    raise exception 'Target part % was not found for character %', v_target_part, v_target_character_id;
  end if;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'load-target-part',
    p_phase_name => 'load-target-part',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'target_part', v_target_part,
      'current_hp', v_target_row.current_hp,
      'armor', v_target_row.armor
    )
  );

  v_phase_started_at := clock_timestamp();
  select *
  into v_special_row
  from public.odyssey_character_body_parts
  where character_id = v_target_character_id
    and part_key = 'Special';
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'load-special-part',
    p_phase_name => 'load-special-part',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'special_found', found,
      'special_current_hp', coalesce(v_special_row.current_hp, 0),
      'special_max_hp', coalesce(v_special_row.max_hp, 0)
    )
  );

  if v_target_part <> 'Special'
     and found
     and v_special_row.max_hp > 0
     and v_special_row.current_hp > 0 then
    v_phase_started_at := clock_timestamp();
    v_special_result := public.odyssey_apply_part_damage(to_jsonb(v_special_row), v_damage_kind, v_amount);
    v_special_hp_loss := greatest(0, v_special_row.current_hp - coalesce((v_special_result->>'current_hp')::integer, 0));
    v_special_crit_applied := greatest(0, coalesce((v_special_result->>'crit_applied')::integer, 0));
    v_overflow_crit := greatest(0, v_special_crit_applied - v_special_hp_loss);

    update public.odyssey_character_body_parts
    set
      current_hp = coalesce((v_special_result->>'current_hp')::integer, current_hp),
      minor = coalesce((v_special_result->>'minor')::integer, minor),
      serious = coalesce((v_special_result->>'serious')::integer, serious),
      critical = coalesce((v_special_result->>'critical')::integer, critical),
      max_critical = coalesce((v_special_result->>'max_critical')::integer, max_critical),
      destroyed = coalesce((v_special_result->>'destroyed')::boolean, destroyed),
      disabled = coalesce((v_special_result->>'disabled')::boolean, disabled),
      updated_at = timezone('utc', now())
    where character_id = v_target_character_id
      and part_key = 'Special';
    v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
    perform public.odyssey_debug_perf(
      p_function_name => v_function_name,
      p_span_name => 'apply-special-part',
      p_phase_name => 'apply-special-part',
      p_trace_id => v_trace_id,
      p_target_character_id => v_target_character_id,
      p_actor_character_id => v_actor_character_id,
      p_room_id => v_room_id,
      p_scene_id => v_scene_id,
      p_duration_ms => v_duration_ms,
      p_metadata => jsonb_build_object(
        'special_hp_loss', v_special_hp_loss,
        'special_crit_applied', v_special_crit_applied,
        'overflow_crit', v_overflow_crit
      )
    );

    if v_overflow_crit > 0 then
      v_target_result := public.odyssey_apply_part_damage(to_jsonb(v_target_row), 'critical', v_overflow_crit);
    else
      v_target_result := to_jsonb(v_target_row) || jsonb_build_object('crit_applied', 0);
    end if;
  else
    v_phase_started_at := clock_timestamp();
    v_target_result := public.odyssey_apply_part_damage(to_jsonb(v_target_row), v_damage_kind, v_amount);
    v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
    perform public.odyssey_debug_perf(
      p_function_name => v_function_name,
      p_span_name => 'apply-target-part',
      p_phase_name => 'apply-target-part',
      p_trace_id => v_trace_id,
      p_target_character_id => v_target_character_id,
      p_actor_character_id => v_actor_character_id,
      p_room_id => v_room_id,
      p_scene_id => v_scene_id,
      p_duration_ms => v_duration_ms,
      p_metadata => jsonb_build_object(
        'target_part', v_target_part,
        'damage_kind', v_damage_kind,
        'amount', v_amount
      )
    );
  end if;

  v_phase_started_at := clock_timestamp();
  update public.odyssey_character_body_parts
  set
    current_hp = coalesce((v_target_result->>'current_hp')::integer, current_hp),
    minor = coalesce((v_target_result->>'minor')::integer, minor),
    serious = coalesce((v_target_result->>'serious')::integer, serious),
    critical = coalesce((v_target_result->>'critical')::integer, critical),
    max_critical = coalesce((v_target_result->>'max_critical')::integer, max_critical),
    destroyed = coalesce((v_target_result->>'destroyed')::boolean, destroyed),
    disabled = coalesce((v_target_result->>'disabled')::boolean, disabled),
    updated_at = timezone('utc', now())
  where character_id = v_target_character_id
    and part_key = v_target_part;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'persist-target-part',
    p_phase_name => 'persist-target-part',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'target_part', v_target_part,
      'current_hp', coalesce((v_target_result->>'current_hp')::integer, 0),
      'critical', coalesce((v_target_result->>'critical')::integer, 0)
    )
  );

  v_phase_started_at := clock_timestamp();
  v_recomputed := public.recompute_odyssey_character_combat_state(v_target_character_id);
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'recompute-combat-state',
    p_phase_name => 'recompute-combat-state',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms
  );

  v_message := format(
    'Damage applied to %s (%s x%s).',
    v_target_part,
    v_damage_kind,
    v_amount
  );

  v_phase_started_at := clock_timestamp();
  insert into public.odyssey_combat_log (
    campaign_id,
    room_id,
    scene_id,
    encounter_id,
    actor_character_id,
    target_character_id,
    event_type,
    message,
    data,
    created_by
  )
  values (
    v_campaign_id,
    v_room_id,
    v_scene_id,
    v_encounter_id,
    v_actor_character_id,
    v_target_character_id,
    'damage',
    v_message,
    jsonb_build_object(
      'target_part', v_target_part,
      'damage_kind', v_damage_kind,
      'amount', v_amount,
      'attack_result', coalesce(p_payload->'attack_result', '{}'::jsonb)
    ),
    v_created_by
  )
  returning jsonb_build_object(
    'event_type', event_type,
    'message', message,
    'created_at', created_at,
    'target_character_id', target_character_id,
    'actor_character_id', actor_character_id
  ) into v_log_entry;
  v_duration_ms := (extract(epoch from clock_timestamp() - v_phase_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'write-combat-log',
    p_phase_name => 'write-combat-log',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms
  );

  v_duration_ms := (extract(epoch from clock_timestamp() - v_total_started_at) * 1000)::numeric(12,2);
  perform public.odyssey_debug_perf(
    p_function_name => v_function_name,
    p_span_name => 'total',
    p_phase_name => 'total',
    p_trace_id => v_trace_id,
    p_target_character_id => v_target_character_id,
    p_actor_character_id => v_actor_character_id,
    p_room_id => v_room_id,
    p_scene_id => v_scene_id,
    p_duration_ms => v_duration_ms,
    p_metadata => jsonb_build_object(
      'target_part', v_target_part,
      'damage_kind', v_damage_kind,
      'amount', v_amount,
      'overflow_crit', v_overflow_crit
    )
  );

  return jsonb_build_object(
    'ok', true,
    'changed_character_ids', jsonb_build_array(v_target_character_id),
    'target_character_id', v_target_character_id,
    'combat_state', v_recomputed->'combat_state',
    'log_entry', v_log_entry
  );
exception
  when others then
    perform public.odyssey_debug_perf(
      p_function_name => v_function_name,
      p_span_name => 'error',
      p_phase_name => 'error',
      p_trace_id => v_trace_id,
      p_target_character_id => v_target_character_id,
      p_actor_character_id => v_actor_character_id,
      p_room_id => v_room_id,
      p_scene_id => v_scene_id,
      p_level => 'error',
      p_duration_ms => (extract(epoch from clock_timestamp() - v_total_started_at) * 1000)::numeric(12,2),
      p_metadata => jsonb_build_object(
        'message', sqlerrm,
        'target_part', v_target_part,
        'damage_kind', v_damage_kind,
        'amount', v_amount
      ),
      p_error_code => sqlstate
    );
    raise;
end;
$body$;

grant execute on function public.upsert_odyssey_character_sheet(jsonb) to anon, authenticated;
grant execute on function public.apply_damage(jsonb) to anon, authenticated;
