insert into public.odyssey_resource_pool_defs (
  code,
  name,
  source_type,
  attribute_def_id,
  default_max_value,
  default_current_value,
  recovery_mode,
  description,
  data,
  tags,
  is_custom,
  sort_order
)
values
  (
    'psionic_energy',
    'Psionic Energy',
    'attribute',
    (select id from public.odyssey_attribute_defs where code = 'psionics'),
    0,
    null,
    'manual',
    'Psionic energy reserve derived from the Psionics attribute.',
    '{"ui_group":"psionics"}'::jsonb,
    '["stage4e","psionic","resource"]'::jsonb,
    false,
    10
  )
on conflict (code) do update
set
  name = excluded.name,
  source_type = excluded.source_type,
  attribute_def_id = excluded.attribute_def_id,
  default_max_value = excluded.default_max_value,
  default_current_value = excluded.default_current_value,
  recovery_mode = excluded.recovery_mode,
  description = excluded.description,
  data = excluded.data,
  tags = excluded.tags,
  is_custom = excluded.is_custom,
  sort_order = excluded.sort_order;

insert into public.odyssey_skill_defs (
  code,
  name,
  category,
  max_level,
  main_attribute_id,
  secondary_attribute_id,
  description,
  tags,
  is_custom,
  sort_order
)
values
  (
    'etheric_strike',
    'Etheric Strike',
    'psionic',
    5,
    (select id from public.odyssey_attribute_defs where code = 'psionics'),
    (select id from public.odyssey_attribute_defs where code = 'willpower'),
    'Offensive psionic strike that materializes force against a target.',
    '["stage4e","psionic","attack"]'::jsonb,
    false,
    110
  ),
  (
    'etheric_coating',
    'Etheric Coating',
    'psionic',
    5,
    (select id from public.odyssey_attribute_defs where code = 'psionics'),
    (select id from public.odyssey_attribute_defs where code = 'willpower'),
    'Protective psionic coating that reinforces the Special body slot.',
    '["stage4e","psionic","defense"]'::jsonb,
    false,
    120
  ),
  (
    'sensory_concentration',
    'Sensory Concentration',
    'psionic',
    3,
    (select id from public.odyssey_attribute_defs where code = 'psionics'),
    (select id from public.odyssey_attribute_defs where code = 'willpower'),
    'Focused psionic enhancement of perception and reaction for a short duration.',
    '["stage4e","psionic","buff"]'::jsonb,
    false,
    130
  )
on conflict (code) do update
set
  name = excluded.name,
  category = excluded.category,
  max_level = excluded.max_level,
  main_attribute_id = excluded.main_attribute_id,
  secondary_attribute_id = excluded.secondary_attribute_id,
  description = excluded.description,
  tags = excluded.tags,
  is_custom = excluded.is_custom,
  sort_order = excluded.sort_order;

insert into public.odyssey_skill_level_requirements (
  skill_def_id,
  level,
  main_attribute_required,
  secondary_attribute_required,
  requires_critical_successes,
  notes
)
select
  skill_def.id,
  requirement.level,
  requirement.main_attribute_required,
  requirement.secondary_attribute_required,
  requirement.requires_critical_successes,
  requirement.notes
from public.odyssey_skill_defs skill_def
join (
  values
    ('etheric_strike', 1, 8, null::integer, false, 'Level 1 requires Psionics 8+.'),
    ('etheric_strike', 2, 10, null::integer, false, 'Level 2 requires Psionics 10+.'),
    ('etheric_strike', 3, 12, 10, false, 'Level 3 requires Psionics 12+ and Willpower 10+.'),
    ('etheric_strike', 4, 14, 11, false, 'Level 4 requires Psionics 14+ and Willpower 11+.'),
    ('etheric_strike', 5, null::integer, null::integer, true, 'Level 5 requires critical successes and GM approval.'),
    ('etheric_coating', 1, 8, null::integer, false, 'Level 1 requires Psionics 8+.'),
    ('etheric_coating', 2, 10, null::integer, false, 'Level 2 requires Psionics 10+.'),
    ('etheric_coating', 3, 12, 10, false, 'Level 3 requires Psionics 12+ and Willpower 10+.'),
    ('etheric_coating', 4, 14, 11, false, 'Level 4 requires Psionics 14+ and Willpower 11+.'),
    ('etheric_coating', 5, null::integer, null::integer, true, 'Level 5 requires critical successes and GM approval.'),
    ('sensory_concentration', 1, 8, null::integer, false, 'Level 1 requires Psionics 8+.'),
    ('sensory_concentration', 2, 10, null::integer, false, 'Level 2 requires Psionics 10+.'),
    ('sensory_concentration', 3, 12, 10, false, 'Level 3 requires Psionics 12+ and Willpower 10+.')
) as requirement(skill_code, level, main_attribute_required, secondary_attribute_required, requires_critical_successes, notes)
  on requirement.skill_code = skill_def.code
on conflict (skill_def_id, level) do update
set
  main_attribute_required = excluded.main_attribute_required,
  secondary_attribute_required = excluded.secondary_attribute_required,
  requires_critical_successes = excluded.requires_critical_successes,
  notes = excluded.notes;

insert into public.odyssey_ability_defs (
  code,
  name,
  ability_kind,
  source_type,
  activation_type,
  target_type,
  effect_mode,
  attack_type,
  linked_skill_id,
  resource_mode,
  resource_pool_code,
  resource_item_code,
  description,
  data,
  effect_data,
  tags,
  is_custom,
  sort_order
)
values
  (
    'etheric_strike',
    'Etheric Strike',
    'attack',
    'psionic',
    'manual',
    'body_part',
    'attack',
    'ranged',
    (select id from public.odyssey_skill_defs where code = 'etheric_strike'),
    'pool',
    'psionic_energy',
    null,
    'Materialized psionic force projected against a target body part.',
    '{"family":"psionic_attack"}'::jsonb,
    '{}'::jsonb,
    '["stage4e","psionic","attack"]'::jsonb,
    false,
    10
  ),
  (
    'etheric_coating',
    'Etheric Coating',
    'defense',
    'psionic',
    'manual',
    'self',
    'grant_special',
    null,
    (select id from public.odyssey_skill_defs where code = 'etheric_coating'),
    'pool',
    'psionic_energy',
    null,
    'Wraps the caster in psionic protection by reinforcing the Special body slot.',
    '{"family":"psionic_defense"}'::jsonb,
    '{}'::jsonb,
    '["stage4e","psionic","defense"]'::jsonb,
    false,
    20
  ),
  (
    'sensory_concentration',
    'Sensory Concentration',
    'buff',
    'psionic',
    'manual',
    'self',
    'apply_effect',
    null,
    (select id from public.odyssey_skill_defs where code = 'sensory_concentration'),
    'pool',
    'psionic_energy',
    null,
    'Temporarily heightens the caster''s perception and reaction.',
    '{"family":"psionic_buff"}'::jsonb,
    '{}'::jsonb,
    '["stage4e","psionic","buff"]'::jsonb,
    false,
    30
  )
on conflict (code) do update
set
  name = excluded.name,
  ability_kind = excluded.ability_kind,
  source_type = excluded.source_type,
  activation_type = excluded.activation_type,
  target_type = excluded.target_type,
  effect_mode = excluded.effect_mode,
  attack_type = excluded.attack_type,
  linked_skill_id = excluded.linked_skill_id,
  resource_mode = excluded.resource_mode,
  resource_pool_code = excluded.resource_pool_code,
  resource_item_code = excluded.resource_item_code,
  description = excluded.description,
  data = excluded.data,
  effect_data = excluded.effect_data,
  tags = excluded.tags,
  is_custom = excluded.is_custom,
  sort_order = excluded.sort_order;

insert into public.odyssey_ability_level_defs (
  ability_def_id,
  ability_level,
  resource_cost,
  cooldown_rounds,
  range_profile_id,
  attack_accuracy_bonus,
  attack_damage_bonus,
  attack_armor_pierce,
  ignore_armor,
  special_armor_value,
  special_max_critical,
  duration_rounds,
  data,
  effect_data
)
values
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_strike'),
    1,
    1,
    0,
    (select id from public.odyssey_range_profile_defs where code = 'pistol_profile'),
    0,
    50,
    0,
    false,
    null,
    null,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_strike'),
    2,
    1,
    0,
    (select id from public.odyssey_range_profile_defs where code = 'pistol_profile'),
    0,
    50,
    0,
    false,
    null,
    null,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_strike'),
    3,
    1,
    0,
    (select id from public.odyssey_range_profile_defs where code = 'rifle_profile'),
    0,
    50,
    0,
    false,
    null,
    null,
    null,
    '{"narrative_note":"At level 3+ the caster may reshape direction, form, and force narratively."}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_strike'),
    4,
    1,
    0,
    (select id from public.odyssey_range_profile_defs where code = 'rifle_profile'),
    0,
    50,
    0,
    false,
    null,
    null,
    null,
    '{"narrative_note":"At level 3+ the caster may reshape direction, form, and force narratively."}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_strike'),
    5,
    1,
    0,
    (select id from public.odyssey_range_profile_defs where code = 'rifle_profile'),
    0,
    50,
    0,
    false,
    null,
    null,
    null,
    '{"narrative_note":"At level 3+ the caster may reshape direction, form, and force narratively."}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_coating'),
    1,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    10,
    1,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_coating'),
    2,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    20,
    1,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_coating'),
    3,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    30,
    2,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_coating'),
    4,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    40,
    2,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'etheric_coating'),
    5,
    2,
    0,
    null,
    0,
    0,
    0,
    false,
    50,
    3,
    null,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'sensory_concentration'),
    1,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    null,
    null,
    2,
    '{"effect_code":"sense_focus_1"}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'sensory_concentration'),
    2,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    null,
    null,
    2,
    '{"effect_code":"sense_focus_2"}'::jsonb,
    '{}'::jsonb
  ),
  (
    (select id from public.odyssey_ability_defs where code = 'sensory_concentration'),
    3,
    1,
    0,
    null,
    0,
    0,
    0,
    false,
    null,
    null,
    2,
    '{"effect_code":"sense_focus_3"}'::jsonb,
    '{}'::jsonb
  )
on conflict (ability_def_id, ability_level) do update
set
  resource_cost = excluded.resource_cost,
  cooldown_rounds = excluded.cooldown_rounds,
  range_profile_id = excluded.range_profile_id,
  attack_accuracy_bonus = excluded.attack_accuracy_bonus,
  attack_damage_bonus = excluded.attack_damage_bonus,
  attack_armor_pierce = excluded.attack_armor_pierce,
  ignore_armor = excluded.ignore_armor,
  special_armor_value = excluded.special_armor_value,
  special_max_critical = excluded.special_max_critical,
  duration_rounds = excluded.duration_rounds,
  data = excluded.data,
  effect_data = excluded.effect_data;
